{
  "vulns": [
    {
      "id": "GHSA-9jmf-237g-qf46",
      "summary": "Django Path Traversal vulnerability",
      "details": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. Derived classes of the `django.core.files.storage.Storage` base class, when they override `generate_filename()` without replicating the file-path validations from the parent class, potentially allow directory traversal via certain inputs during a `save()` call. (Built-in Storage sub-classes are unaffected.)",
      "aliases": [
        "CVE-2024-39330",
        "PYSEC-2024-58"
      ],
      "modified": "2024-07-10T21:59:19.394008Z",
      "published": "2024-07-10T06:33:52Z",
      "database_specific": {
        "github_reviewed_at": "2024-07-10T21:41:33Z",
        "github_reviewed": true,
        "severity": "HIGH",
        "cwe_ids": [
          "CWE-22"
        ],
        "nvd_published_at": "2024-07-10T05:15:12Z"
      },
      "references": [
        {
          "type": "ADVISORY",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39330"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security"
        },
        {
          "type": "PACKAGE",
          "url": "https://github.com/django/django"
        },
        {
          "type": "WEB",
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                }
              ]
            }
          ],
          "versions": [
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/07/GHSA-9jmf-237g-qf46/GHSA-9jmf-237g-qf46.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/07/GHSA-9jmf-237g-qf46/GHSA-9jmf-237g-qf46.json"
          }
        }
      ],
      "schema_version": "1.6.0",
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
        },
        {
          "type": "CVSS_V4",
          "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N"
        }
      ]
    },
    {
      "id": "GHSA-f6f8-9mx6-9mx2",
      "summary": "Django vulnerable to Denial of Service",
      "details": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. `get_supported_language_variant()` was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
      "aliases": [
        "PYSEC-2024-59"
      ],
      "modified": "2024-07-10T21:59:14.676348Z",
      "published": "2024-07-10T06:33:52Z",
      "database_specific": {
        "github_reviewed_at": "2024-07-10T21:43:25Z",
        "github_reviewed": true,
        "severity": "HIGH",
        "cwe_ids": [
          "CWE-770"
        ],
        "nvd_published_at": "2024-07-10T05:15:12Z"
      },
      "references": [
        {
          "type": "ADVISORY",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39614"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security"
        },
        {
          "type": "PACKAGE",
          "url": "https://github.com/django/django"
        },
        {
          "type": "WEB",
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases"
        }
      ],
      "affected": [],
      "schema_version": "1.6.0",
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        {
          "type": "CVSS_V4",
          "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N"
        }
      ]
    },
    {
      "id": "GHSA-qg2p-9jwr-mmqf",
      "summary": "Django vulnerable to Denial of Service",
      "details": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
      "aliases": [
        "CVE-2024-38875",
        "PYSEC-2024-56"
      ],
      "modified": "2024-07-10T21:59:20.053812Z",
      "published": "2024-07-10T06:33:52Z",
      "database_specific": {
        "github_reviewed_at": "2024-07-10T21:41:03Z",
        "github_reviewed": true,
        "severity": "HIGH",
        "cwe_ids": [
          "CWE-770"
        ],
        "nvd_published_at": "2024-07-10T05:15:12Z"
      },
      "references": [
        {
          "type": "ADVISORY",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-38875"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security"
        },
        {
          "type": "PACKAGE",
          "url": "https://github.com/django/django"
        },
        {
          "type": "WEB",
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/07/GHSA-qg2p-9jwr-mmqf/GHSA-qg2p-9jwr-mmqf.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                }
              ]
            }
          ],
          "versions": [
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/07/GHSA-qg2p-9jwr-mmqf/GHSA-qg2p-9jwr-mmqf.json"
          }
        }
      ],
      "schema_version": "1.6.0",
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        {
          "type": "CVSS_V4",
          "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N"
        }
      ]
    },
    {
      "id": "GHSA-vm8q-m57g-pff3",
      "summary": "Regular expression denial-of-service in Django",
      "details": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
      "aliases": [
        "BIT-django-2024-27351",
        "CVE-2024-27351",
        "PYSEC-2024-47"
      ],
      "modified": "2024-07-03T21:40:46.910597Z",
      "published": "2024-03-15T21:30:43Z",
      "database_specific": {
        "github_reviewed_at": "2024-03-18T20:36:41Z",
        "github_reviewed": true,
        "severity": "MODERATE",
        "cwe_ids": [
          "CWE-1333"
        ],
        "nvd_published_at": "2024-03-15T20:15:09Z"
      },
      "references": [
        {
          "type": "ADVISORY",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27351"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/072963e4c4d0b3a7a8c5412bc0c7d27d1a9c3521"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/3394fc6132436eca89e997083bae9985fb7e761e"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/3c9a2771cc80821e041b16eb36c1c37af5349d4a"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/5.0/releases/security"
        },
        {
          "type": "PACKAGE",
          "url": "https://github.com/django/django"
        },
        {
          "type": "WEB",
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-47.yaml"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX"
        },
        {
          "type": "WEB",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6"
        },
        {
          "type": "WEB",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D"
        },
        {
          "type": "WEB",
          "url": "https://www.djangoproject.com/weblog/2024/mar/04/security-releases"
        },
        {
          "type": "WEB",
          "url": "http://www.openwall.com/lists/oss-security/2024/03/04/1"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "3.2"
                },
                {
                  "fixed": "3.2.25"
                }
              ]
            }
          ],
          "versions": [
            "3.2",
            "3.2.1",
            "3.2.10",
            "3.2.11",
            "3.2.12",
            "3.2.13",
            "3.2.14",
            "3.2.15",
            "3.2.16",
            "3.2.17",
            "3.2.18",
            "3.2.19",
            "3.2.2",
            "3.2.20",
            "3.2.21",
            "3.2.22",
            "3.2.23",
            "3.2.24",
            "3.2.3",
            "3.2.4",
            "3.2.5",
            "3.2.6",
            "3.2.7",
            "3.2.8",
            "3.2.9"
          ],
          "ecosystem_specific": {
            "affected_functions": [
              "django.utils.text.Truncator.words"
            ]
          },
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/03/GHSA-vm8q-m57g-pff3/GHSA-vm8q-m57g-pff3.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.11"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9"
          ],
          "ecosystem_specific": {
            "affected_functions": [
              "django.utils.text.Truncator.words"
            ]
          },
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/03/GHSA-vm8q-m57g-pff3/GHSA-vm8q-m57g-pff3.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.3"
                }
              ]
            }
          ],
          "versions": [
            "5.0",
            "5.0.1",
            "5.0.2"
          ],
          "ecosystem_specific": {
            "affected_functions": [
              "django.utils.text.Truncator.words"
            ]
          },
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/03/GHSA-vm8q-m57g-pff3/GHSA-vm8q-m57g-pff3.json"
          }
        }
      ],
      "schema_version": "1.6.0",
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:H"
        }
      ]
    },
    {
      "id": "GHSA-x7q2-wr7g-xqmf",
      "summary": "Django vulnerable to user enumeration attack",
      "details": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The `django.contrib.auth.backends.ModelBackend.authenticate()` method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password.",
      "aliases": [
        "CVE-2024-39329",
        "PYSEC-2024-57"
      ],
      "modified": "2024-07-11T17:30:56.841737Z",
      "published": "2024-07-10T06:33:52Z",
      "database_specific": {
        "github_reviewed_at": "2024-07-10T21:42:19Z",
        "github_reviewed": true,
        "severity": "MODERATE",
        "cwe_ids": [
          "CWE-208"
        ],
        "nvd_published_at": "2024-07-10T05:15:12Z"
      },
      "references": [
        {
          "type": "ADVISORY",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39329"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security"
        },
        {
          "type": "PACKAGE",
          "url": "https://github.com/django/django"
        },
        {
          "type": "WEB",
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                }
              ]
            }
          ],
          "versions": [
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/07/GHSA-x7q2-wr7g-xqmf/GHSA-x7q2-wr7g-xqmf.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/07/GHSA-x7q2-wr7g-xqmf/GHSA-x7q2-wr7g-xqmf.json"
          }
        }
      ],
      "schema_version": "1.6.0",
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
        },
        {
          "type": "CVSS_V4",
          "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N"
        }
      ]
    },
    {
      "id": "GHSA-xxj9-f6rv-m3x4",
      "summary": "Django denial-of-service attack in the intcomma template filter",
      "details": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings.",
      "aliases": [
        "BIT-django-2024-24680",
        "CVE-2024-24680",
        "PYSEC-2024-28"
      ],
      "modified": "2024-04-20T03:46:18.868330Z",
      "published": "2024-02-07T00:30:25Z",
      "database_specific": {
        "github_reviewed_at": "2024-02-07T17:32:14Z",
        "github_reviewed": true,
        "severity": "MODERATE",
        "cwe_ids": [],
        "nvd_published_at": "2024-02-06T22:16:15Z"
      },
      "references": [
        {
          "type": "ADVISORY",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-24680"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2"
        },
        {
          "type": "WEB",
          "url": "https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/5.0/releases/security"
        },
        {
          "type": "PACKAGE",
          "url": "https://github.com/django/django"
        },
        {
          "type": "WEB",
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-28.yaml"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX"
        },
        {
          "type": "WEB",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6"
        },
        {
          "type": "WEB",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D"
        },
        {
          "type": "WEB",
          "url": "https://www.djangoproject.com/weblog/2024/feb/06/security-releases"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "0"
                },
                {
                  "fixed": "3.2.24"
                }
              ]
            }
          ],
          "versions": [
            "1.0.1",
            "1.0.2",
            "1.0.3",
            "1.0.4",
            "1.1",
            "1.1.1",
            "1.1.2",
            "1.1.3",
            "1.1.4",
            "1.10",
            "1.10.1",
            "1.10.2",
            "1.10.3",
            "1.10.4",
            "1.10.5",
            "1.10.6",
            "1.10.7",
            "1.10.8",
            "1.10a1",
            "1.10b1",
            "1.10rc1",
            "1.11",
            "1.11.1",
            "1.11.10",
            "1.11.11",
            "1.11.12",
            "1.11.13",
            "1.11.14",
            "1.11.15",
            "1.11.16",
            "1.11.17",
            "1.11.18",
            "1.11.2",
            "1.11.20",
            "1.11.21",
            "1.11.22",
            "1.11.23",
            "1.11.24",
            "1.11.25",
            "1.11.26",
            "1.11.27",
            "1.11.28",
            "1.11.29",
            "1.11.3",
            "1.11.4",
            "1.11.5",
            "1.11.6",
            "1.11.7",
            "1.11.8",
            "1.11.9",
            "1.11a1",
            "1.11b1",
            "1.11rc1",
            "1.2",
            "1.2.1",
            "1.2.2",
            "1.2.3",
            "1.2.4",
            "1.2.5",
            "1.2.6",
            "1.2.7",
            "1.3",
            "1.3.1",
            "1.3.2",
            "1.3.3",
            "1.3.4",
            "1.3.5",
            "1.3.6",
            "1.3.7",
            "1.4",
            "1.4.1",
            "1.4.10",
            "1.4.11",
            "1.4.12",
            "1.4.13",
            "1.4.14",
            "1.4.15",
            "1.4.16",
            "1.4.17",
            "1.4.18",
            "1.4.19",
            "1.4.2",
            "1.4.20",
            "1.4.21",
            "1.4.22",
            "1.4.3",
            "1.4.4",
            "1.4.5",
            "1.4.6",
            "1.4.7",
            "1.4.8",
            "1.4.9",
            "1.5",
            "1.5.1",
            "1.5.10",
            "1.5.11",
            "1.5.12",
            "1.5.2",
            "1.5.3",
            "1.5.4",
            "1.5.5",
            "1.5.6",
            "1.5.7",
            "1.5.8",
            "1.5.9",
            "1.6",
            "1.6.1",
            "1.6.10",
            "1.6.11",
            "1.6.2",
            "1.6.3",
            "1.6.4",
            "1.6.5",
            "1.6.6",
            "1.6.7",
            "1.6.8",
            "1.6.9",
            "1.7",
            "1.7.1",
            "1.7.10",
            "1.7.11",
            "1.7.2",
            "1.7.3",
            "1.7.4",
            "1.7.5",
            "1.7.6",
            "1.7.7",
            "1.7.8",
            "1.7.9",
            "1.8",
            "1.8.1",
            "1.8.10",
            "1.8.11",
            "1.8.12",
            "1.8.13",
            "1.8.14",
            "1.8.15",
            "1.8.16",
            "1.8.17",
            "1.8.18",
            "1.8.19",
            "1.8.2",
            "1.8.3",
            "1.8.4",
            "1.8.5",
            "1.8.6",
            "1.8.7",
            "1.8.8",
            "1.8.9",
            "1.8a1",
            "1.8b1",
            "1.8b2",
            "1.8c1",
            "1.9",
            "1.9.1",
            "1.9.10",
            "1.9.11",
            "1.9.12",
            "1.9.13",
            "1.9.2",
            "1.9.3",
            "1.9.4",
            "1.9.5",
            "1.9.6",
            "1.9.7",
            "1.9.8",
            "1.9.9",
            "1.9a1",
            "1.9b1",
            "1.9rc1",
            "1.9rc2",
            "2.0",
            "2.0.1",
            "2.0.10",
            "2.0.12",
            "2.0.13",
            "2.0.2",
            "2.0.3",
            "2.0.4",
            "2.0.5",
            "2.0.6",
            "2.0.7",
            "2.0.8",
            "2.0.9",
            "2.0a1",
            "2.0b1",
            "2.0rc1",
            "2.1",
            "2.1.1",
            "2.1.10",
            "2.1.11",
            "2.1.12",
            "2.1.13",
            "2.1.14",
            "2.1.15",
            "2.1.2",
            "2.1.3",
            "2.1.4",
            "2.1.5",
            "2.1.7",
            "2.1.8",
            "2.1.9",
            "2.1a1",
            "2.1b1",
            "2.1rc1",
            "2.2",
            "2.2.1",
            "2.2.10",
            "2.2.11",
            "2.2.12",
            "2.2.13",
            "2.2.14",
            "2.2.15",
            "2.2.16",
            "2.2.17",
            "2.2.18",
            "2.2.19",
            "2.2.2",
            "2.2.20",
            "2.2.21",
            "2.2.22",
            "2.2.23",
            "2.2.24",
            "2.2.25",
            "2.2.26",
            "2.2.27",
            "2.2.28",
            "2.2.3",
            "2.2.4",
            "2.2.5",
            "2.2.6",
            "2.2.7",
            "2.2.8",
            "2.2.9",
            "2.2a1",
            "2.2b1",
            "2.2rc1",
            "3.0",
            "3.0.1",
            "3.0.10",
            "3.0.11",
            "3.0.12",
            "3.0.13",
            "3.0.14",
            "3.0.2",
            "3.0.3",
            "3.0.4",
            "3.0.5",
            "3.0.6",
            "3.0.7",
            "3.0.8",
            "3.0.9",
            "3.0a1",
            "3.0b1",
            "3.0rc1",
            "3.1",
            "3.1.1",
            "3.1.10",
            "3.1.11",
            "3.1.12",
            "3.1.13",
            "3.1.14",
            "3.1.2",
            "3.1.3",
            "3.1.4",
            "3.1.5",
            "3.1.6",
            "3.1.7",
            "3.1.8",
            "3.1.9",
            "3.1a1",
            "3.1b1",
            "3.1rc1",
            "3.2",
            "3.2.1",
            "3.2.10",
            "3.2.11",
            "3.2.12",
            "3.2.13",
            "3.2.14",
            "3.2.15",
            "3.2.16",
            "3.2.17",
            "3.2.18",
            "3.2.19",
            "3.2.2",
            "3.2.20",
            "3.2.21",
            "3.2.22",
            "3.2.23",
            "3.2.3",
            "3.2.4",
            "3.2.5",
            "3.2.6",
            "3.2.7",
            "3.2.8",
            "3.2.9",
            "3.2a1",
            "3.2b1",
            "3.2rc1"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/02/GHSA-xxj9-f6rv-m3x4/GHSA-xxj9-f6rv-m3x4.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.10"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/02/GHSA-xxj9-f6rv-m3x4/GHSA-xxj9-f6rv-m3x4.json"
          }
        },
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.2"
                }
              ]
            }
          ],
          "versions": [
            "5.0",
            "5.0.1"
          ],
          "database_specific": {
            "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/02/GHSA-xxj9-f6rv-m3x4/GHSA-xxj9-f6rv-m3x4.json"
          }
        }
      ],
      "schema_version": "1.6.0",
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ]
    },
    {
      "id": "PYSEC-2024-28",
      "details": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings.",
      "aliases": [
        "BIT-django-2024-24680",
        "CVE-2024-24680",
        "GHSA-xxj9-f6rv-m3x4"
      ],
      "modified": "2024-02-16T08:26:32.550177Z",
      "published": "2024-02-06T22:16:00Z",
      "references": [
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/5.0/releases/security/"
        },
        {
          "type": "ARTICLE",
          "url": "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "3.2"
                },
                {
                  "fixed": "3.2.24"
                },
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.10"
                },
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.2"
                }
              ]
            }
          ],
          "versions": [
            "3.2",
            "3.2.1",
            "3.2.10",
            "3.2.11",
            "3.2.12",
            "3.2.13",
            "3.2.14",
            "3.2.15",
            "3.2.16",
            "3.2.17",
            "3.2.18",
            "3.2.19",
            "3.2.2",
            "3.2.20",
            "3.2.21",
            "3.2.22",
            "3.2.23",
            "3.2.3",
            "3.2.4",
            "3.2.5",
            "3.2.6",
            "3.2.7",
            "3.2.8",
            "3.2.9",
            "4.2",
            "4.2.1",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9",
            "5.0",
            "5.0.1"
          ],
          "database_specific": {
            "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2024-28.yaml"
          }
        }
      ],
      "schema_version": "1.6.0"
    },
    {
      "id": "PYSEC-2024-47",
      "details": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
      "aliases": [
        "BIT-django-2024-27351",
        "CVE-2024-27351",
        "GHSA-vm8q-m57g-pff3"
      ],
      "modified": "2024-07-02T08:12:21.263863Z",
      "published": "2024-03-15T20:15:00Z",
      "references": [
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/5.0/releases/security/"
        },
        {
          "type": "ARTICLE",
          "url": "https://www.djangoproject.com/weblog/2024/mar/04/security-releases/"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "3.2"
                },
                {
                  "fixed": "3.2.25"
                },
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.11"
                },
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.3"
                }
              ]
            }
          ],
          "versions": [
            "3.2",
            "3.2.1",
            "3.2.10",
            "3.2.11",
            "3.2.12",
            "3.2.13",
            "3.2.14",
            "3.2.15",
            "3.2.16",
            "3.2.17",
            "3.2.18",
            "3.2.19",
            "3.2.2",
            "3.2.20",
            "3.2.21",
            "3.2.22",
            "3.2.23",
            "3.2.24",
            "3.2.3",
            "3.2.4",
            "3.2.5",
            "3.2.6",
            "3.2.7",
            "3.2.8",
            "3.2.9",
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9",
            "5.0",
            "5.0.1",
            "5.0.2"
          ],
          "database_specific": {
            "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2024-47.yaml"
          }
        }
      ],
      "schema_version": "1.6.0"
    },
    {
      "id": "PYSEC-2024-56",
      "details": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
      "aliases": [
        "CVE-2024-38875",
        "GHSA-qg2p-9jwr-mmqf"
      ],
      "modified": "2024-07-10T21:59:20.053812Z",
      "published": "2024-07-10T05:15:00Z",
      "references": [
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security/"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "ARTICLE",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                },
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9",
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2024-56.yaml"
          }
        }
      ],
      "schema_version": "1.6.0"
    },
    {
      "id": "PYSEC-2024-57",
      "details": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password.",
      "aliases": [
        "CVE-2024-39329",
        "GHSA-x7q2-wr7g-xqmf"
      ],
      "modified": "2024-07-10T21:59:20.657618Z",
      "published": "2024-07-10T05:15:00Z",
      "references": [
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security/"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "ARTICLE",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                },
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9",
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2024-57.yaml"
          }
        }
      ],
      "schema_version": "1.6.0"
    },
    {
      "id": "PYSEC-2024-58",
      "details": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. Derived classes of the django.core.files.storage.Storage base class, when they override generate_filename() without replicating the file-path validations from the parent class, potentially allow directory traversal via certain inputs during a save() call. (Built-in Storage sub-classes are unaffected.)",
      "aliases": [
        "CVE-2024-39330",
        "GHSA-9jmf-237g-qf46"
      ],
      "modified": "2024-07-10T21:59:19.394008Z",
      "published": "2024-07-10T05:15:00Z",
      "references": [
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security/"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "ARTICLE",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                },
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9",
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2024-58.yaml"
          }
        }
      ],
      "schema_version": "1.6.0"
    },
    {
      "id": "PYSEC-2024-59",
      "details": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
      "aliases": [
        "CVE-2024-39614",
        "GHSA-f6f8-9mx6-9mx2"
      ],
      "modified": "2024-07-10T21:59:14.676348Z",
      "published": "2024-07-10T05:15:00Z",
      "references": [
        {
          "type": "WEB",
          "url": "https://docs.djangoproject.com/en/dev/releases/security/"
        },
        {
          "type": "WEB",
          "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
          "type": "ARTICLE",
          "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "django",
            "ecosystem": "PyPI",
            "purl": "pkg:pypi/django"
          },
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "5.0"
                },
                {
                  "fixed": "5.0.7"
                },
                {
                  "introduced": "4.2"
                },
                {
                  "fixed": "4.2.14"
                }
              ]
            }
          ],
          "versions": [
            "4.2",
            "4.2.1",
            "4.2.10",
            "4.2.11",
            "4.2.12",
            "4.2.13",
            "4.2.2",
            "4.2.3",
            "4.2.4",
            "4.2.5",
            "4.2.6",
            "4.2.7",
            "4.2.8",
            "4.2.9",
            "5.0",
            "5.0.1",
            "5.0.2",
            "5.0.3",
            "5.0.4",
            "5.0.5",
            "5.0.6"
          ],
          "database_specific": {
            "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2024-59.yaml"
          }
        }
      ],
      "schema_version": "1.6.0"
    }
  ]
}